"
I am a dedicated error used to check the the CaptureErrors setting is working as intended
"
Class {
	#name : 'BCFailingOnPurposeForTestError',
	#superclass : 'Error',
	#category : 'BeautifulComments-Tests',
	#package : 'BeautifulComments',
	#tag : 'Tests'
}
